inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  SuggestExtensions: false
  NewCops: enable

Layout/LineLength:
  Max: 120
  Exclude:
    - 'test/golden_rules_test.rb'
    - 'test/languagetool_rules_test.rb'
